version: '3.3'
services:
  api:
    container_name: forecastAPI
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    container_name: dbMongo
    image: mongo
    ports:
      - "27017:27017"